
default_platform(:ios)

ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"

platform :ios do

  desc "Deploy a new version to the App Store"
  lane :release do

    precheck

    # Note: Xcode Auto-manage signing is enabled
    # good enough for now since I'm not setting up a build server
    # for this project

    increment_build_number
    commit_version_bump(
      message: 'Build Version Bump by fastlane',
      force: true
    )

    gym(
    	scheme: "ResearchAssistant",
    	export_method: "app-store"
    )
    
    deliver(
      submit_for_review: false,
      force: true,
      automatic_release: false
    )

    build_number = Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
    add_git_tag(tag: "appstore-#{get_version_number}(#{build_number})")

    push_to_git_remote
  end
end
